### ISSUE TITLE
Gaps in deprecation strikethrough

### ISSUE THREAD

**Issue by danirabbit** [flobrosch/valadoc-org#13]
Currently there are gaps in the strikethrough on some deprecated items

![bug](https://cloud.githubusercontent.com/assets/1713819/12167767/213794c0-b4fc-11e5-924a-ef60f260857c.png)

**Comment by danirabbit** [comment]
@benwaffle Do you remember which page you reproduced this issue on? Can you still reproduce it?

**Comment by benwaffle** [comment]
looks fine now
