### ISSUE TITLE
Install links are broken

### ISSUE THREAD

**Issue by bilelmoussaoui** [flobrosch/valadoc-org#25]
Install links for every package is broken :/ 

``` bash
Not Found

The requested document was not found on this server.
Web Server at valadoc.org
```

**Comment by flobrosch** [comment]
Thank you for your report. Catalog files are unfortunately deprecated nowadays. I dropped all remaining links.

**Comment by danirabbit** [comment]
You can see the Install links on each package page. For example: http://valadoc.org/#!wiki=dbus-glib-1/index

**Comment by flobrosch** [comment]
Yeah, already dropped them there. I am about to uploading the changes.
