### ISSUE TITLE
Add Gnome-Online-Accounts documentation

### ISSUE THREAD

**Issue by jangernert** [flobrosch/valadoc-org#30]
As of [this commit](https://git.gnome.org/browse/gnome-online-accounts/commit/?id=8adb1e6db6b23a01dc3005a7f2d7a577d32ac72e) a few days ago gnome-online-accounts has vala bindings.
In the corresponding [bug report](https://bugzilla.gnome.org/show_bug.cgi?id=759571) Debarshi Ray told me to report this issue against valadoc.org because he has no control over valadoc.org.
So please add the documentation for goa to valadoc.org :)

**Comment by jangernert** [comment]
I just c&p'ed the meta-data from another package and changed everything according to goa and proposed a merge. No idea if what I did was correct :D 
https://github.com/flobrosch/valadoc-org/pull/31

**Comment by flobrosch** [comment]
Hey jangernert

This is unfortunately a little bit more complicated than this. The first step is to ask nemequ to add the vapi and gir to his vala-girs repository. I did that yesterday. I am going to extend our readme-file about adding new packages soon.

Flo
