### ISSUE TITLE
Running on Fedora

### ISSUE THREAD

**Issue by meghprkh** [flobrosch/valadoc-org#42]
Can you please tell how to make this work in Fedora and also add instructions to readme ?

I am unable to find the valadoc package on fedora

**Comment by benwaffle** [comment]
This repo is for http://valadoc.org, not the valadoc tool

**Comment by flobrosch** [comment]
Hey,

As benwaffle explained, this repository contains the code used to build valadoc.org and does not include the documentation generator. This package is only useful for developers who want to contribute to valadoc.org.

You can find valadocs repository here:
    https://git.gnome.org/browse/valadoc/

**Comment by meghprkh** [comment]
I was talking about valadoc-org only, but I was unable to make valadoc-org even after compiling and installing valadoc because Fedora doesnot add /usr/local directories to `LD_CONFIG_PATH` and `PKG_CONFIG_PATH`

Sorry my fault
