### ISSUE TITLE
Add a version field for documentation

### ISSUE THREAD

**Issue by danirabbit** [flobrosch/valadoc-org#44]
Something that would be useful (because of the nature of distros), is what package versions an API was last changed by. For example, someone just asked about gtk.stacksidebar and why it's not working in elementary OS. The reason is that it is new to gtk 3.16, and we ship gtk 3.14. If the docs said something like "since gtk 3.16" that would be awesome.

**Comment by flobrosch** [comment]
I agree. I already added proper version information to valac/vapigen/vapis as foundation. We only have to pick up the data and render it.
